version: "3.9"
services:
  backend-api:
    image: ghcr.io/arras-labs/backend-api:${TAG:-latest}
    container_name: backend-api
    environment:
      - NODE_ENV=development
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on: [comms-service]

  web-app:
    image: ghcr.io/arras-labs/web-app:${TAG:-latest}
    container_name: web-app
    environment:
      - NODE_ENV=development
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on: [backend-api]

  comms-service:
    image: ghcr.io/arras-labs/comms-service:${TAG:-latest}
    container_name: comms-service
    environment:
      - NODE_ENV=development
